const STAFF_MIN = 2;
const STAFF_MAX = 10;
const TEXT_MIN = 1;
const TEXT_MAX = 5;
const YEARS_RANGE = 100;

const FILMS_LIST_QUANTITY = 20;
const FILMS_LIST_EXTRA_QUANTITY = 2;
const FILM_BLOCK_SIZE = 5;

export {STAFF_MIN, STAFF_MAX, TEXT_MIN, TEXT_MAX, YEARS_RANGE, FILMS_LIST_QUANTITY, FILMS_LIST_EXTRA_QUANTITY, FILM_BLOCK_SIZE};
